"""Ver 1.0 info==null

Revision ID: 42426b455539
Revises: aa3e157f3760
Create Date: 2024-07-08 01:25:14.648221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42426b455539'
down_revision: Union[str, None] = 'aa3e157f3760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_tmp')
    op.add_column('Days', sa.Column('type', sa.String(), nullable=False))
    op.add_column('Days', sa.Column('info', sa.String(), nullable=True))
    op.drop_column('Days', 'Info')
    op.drop_column('Days', 'Type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Days', sa.Column('Type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Days', sa.Column('Info', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Days', 'info')
    op.drop_column('Days', 'type')
    op.create_table('tmp_tmp',

    )
    # ### end Alembic commands ###
